# Generated by Django 5.2.3 on 2025-09-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.board'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_type',
            field=models.CharField(max_length=255),
        ),
    ]
