# Generated by Django 5.2.3 on 2025-09-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_classwisesubject_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classwisesubject',
            name='name',
        ),
        migrations.AddField(
            model_name='classwisesubject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.subject'),
        ),
    ]
