# Generated by Django 5.2.3 on 2025-09-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_remove_classwisesubject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
