# Generated by Django 5.2.3 on 2025-09-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.classwisesubject'),
        ),
    ]
