# Generated by Django 5.2.3 on 2025-09-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestionTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.TextField()),
            ],
            options={
                'db_table': 'custom_question_type_detail',
            },
        ),
        migrations.CreateModel(
            name='DetailQuestionPaperScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_one_mark_questions', models.IntegerField()),
                ('total_two_mark_questions', models.IntegerField()),
                ('total_four_mark_questions', models.IntegerField()),
                ('one_mark_answer_word_count', models.IntegerField()),
                ('two_mark_answer_word_count', models.IntegerField()),
                ('four_mark_answer_word_count', models.IntegerField()),
            ],
            options={
                'db_table': 'question_paper_detail',
            },
        ),
        migrations.CreateModel(
            name='ServiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_question',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, default=0, null=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('very challenging', 'Very Challenging')], max_length=20)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(default='')),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('answer_explanation', models.TextField(default='')),
                ('learning_outcome', models.TextField(default='')),
                ('question_type', models.CharField(choices=[('objective 1 mark', 'Objective one mark'), ('subjective 1 mark', 'Subjective one mark'), ('subjective 2 mark', 'Subjective two mark'), ('subjective 4 mark', 'Subjective four mark'), ('case based', 'Case Based')], default='Miscellaneous', max_length=50)),
                ('bloom_level', models.CharField(default='Understand', max_length=250)),
                ('skill_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('learning_competency', models.CharField(blank=True, max_length=255, null=True)),
                ('language_competency', models.CharField(blank=True, max_length=255, null=True)),
                ('is_regenerated', models.BooleanField(default=False)),
                ('parent_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_question_parent_id', to='question.questionanswer')),
                ('replaced_for_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_question_id', to='question.questionanswer')),
            ],
            options={
                'db_table': 'question_answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=5)),
                ('language', models.CharField(max_length=50)),
                ('paper_type', models.CharField(choices=[('S', 'Subjective'), ('O', 'Objective'), ('SO', 'Hybrid')], default='hybrid', max_length=20)),
                ('learning_objective', models.TextField(blank=True, null=True)),
                ('topic', models.JSONField(blank=True, null=True)),
                ('sub_topic', models.JSONField(blank=True, null=True)),
                ('blooms_taxonomy', models.JSONField(null=True)),
                ('is_generated_correct', models.BooleanField(default=True)),
                ('easy_percentage', models.IntegerField(default=25)),
                ('medium_percentage', models.IntegerField(default=50)),
                ('difficult_percentage', models.IntegerField(default=20)),
                ('very_challenging_percentage', models.IntegerField(default=5)),
                ('generation_type', models.CharField(choices=[('auto', 'Auto'), ('custom', 'Custom')], default='auto', max_length=10)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.board')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.chapter')),
                ('service_type', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='utils.servicetype')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.subject')),
            ],
            options={
                'db_table': 'question_papers',
            },
        ),
    ]
