# Generated by Django 5.2.3 on 2025-06-11 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('paper_type', models.CharField(choices=[('S', 'Subjective'), ('O', 'Objective'), ('SO', 'Hybrid')], max_length=20)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('numerical', 'Numerical')], max_length=50)),
                ('detail', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('marks', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], max_length=20)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(default='')),
                ('replaced_for_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.question')),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionpaper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
