# Generated by Django 5.2.3 on 2025-09-04 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question_paper', to='question.questionpaper'),
        ),
        migrations.AddField(
            model_name='detailquestionpaperscheme',
            name='question_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.questionpaper'),
        ),
        migrations.AddField(
            model_name='servicequestion',
            name='base_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_type_subject', to='utils.subject'),
        ),
        migrations.AddField(
            model_name='servicequestion',
            name='grade_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_question_grade_end', to='utils.standard'),
        ),
        migrations.AddField(
            model_name='servicequestion',
            name='grade_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_question_grade_start', to='utils.standard'),
        ),
        migrations.AddField(
            model_name='servicequestion',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_service_type', to='question.customquestiontypedetail'),
        ),
        migrations.AddField(
            model_name='servicequestion',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type_per_question', to='utils.servicetype'),
        ),
    ]
