# Generated by Django 5.2.3 on 2025-06-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_questiontype'),
        ('question', '0002_alter_question_table_alter_questionpaper_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailQuestionPaperScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_one_mark_questions', models.IntegerField()),
                ('total_two_mark_questions', models.IntegerField()),
                ('total_four_mark_questions', models.IntegerField()),
                ('one_mark_answer_word_count', models.IntegerField()),
                ('two_mark_answer_word_count', models.IntegerField()),
                ('four_mark_answer_word_count', models.IntegerField()),
            ],
            options={
                'db_table': 'question_paper_detail',
            },
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='blooms_taxonomy',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.board'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.chapter'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='is_generated_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='learning_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='sub_topic',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='topic',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detail', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('marks', models.IntegerField()),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], max_length=20)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(default='')),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_explanation', models.TextField()),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionpaper')),
                ('replaced_for_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.questionanswer')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.questiontype')),
            ],
            options={
                'db_table': 'question_answer',
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
