# Generated by Django 5.2.3 on 2025-06-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_detailquestionpaperscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailquestionpaperscheme',
            name='question_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.questionpaper'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='difficult_percentage',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='easy_percentage',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='medium_percentage',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='very_challenging_percentage',
            field=models.IntegerField(default=5),
        ),
    ]
