# Generated by Django 5.2.3 on 2025-06-18 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_detailquestionpaperscheme_question_paper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_type',
            field=models.CharField(choices=[('S', 'Subjective'), ('O', 'Objective'), ('SO', 'Hybrid')], default='hybrid', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='total_marks',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='total_questions',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
