# Generated by Django 5.2.3 on 2025-06-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_questionpaper_paper_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='generation_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('custom', 'Custom')], default='auto', max_length=10),
        ),
    ]
