# Generated by Django 5.2.3 on 2025-06-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_questionpaper_generation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='learning_outcome',
            field=models.TextField(default=''),
        ),
    ]
