# Generated by Django 5.2.3 on 2025-06-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_questionanswer_learning_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestionTypeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'custom_question_type_detail',
            },
        ),
    ]
