# Generated by Django 5.2.3 on 2025-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_customquestiontypedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('very challenging', 'Very Challenging')], max_length=20),
        ),
    ]
