# Generated by Django 5.2.3 on 2025-07-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_questiontype_servicetype_and_more'),
        ('question', '0009_alter_questionanswer_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='service_type',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='base.servicetype'),
        ),
    ]
