# Generated by Django 5.2.3 on 2025-07-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_questionpaper_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='type',
        ),
    ]
