# Generated by Django 5.2.3 on 2025-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_remove_questionanswer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='bloom_level',
            field=models.CharField(default='Understand', max_length=250),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_type',
            field=models.CharField(choices=[('objective 1 mark', 'Objective one mark'), ('subjective 1 mark', 'Subjective one mark'), ('subjective 2 mark', 'Subjective two mark'), ('subjective 4 mark', 'Subjective four mark'), ('case based', 'Case Based')], default='Miscellaneous', max_length=50),
        ),
    ]
