# Generated by Django 5.2.3 on 2025-07-21 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_questionanswer_bloom_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='parent_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_question_parent_id', to='question.questionanswer'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_explanation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='replaced_for_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_question_id', to='question.questionanswer'),
        ),
    ]
