# Generated by Django 5.2.3 on 2025-07-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_questionanswer_parent_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
