# Generated by Django 5.2.3 on 2025-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_alter_questionanswer_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='skill_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
