# Generated by Django 5.2.3 on 2025-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_questionanswer_skill_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='total_questions',
            field=models.IntegerField(default=5),
        ),
    ]
