# Generated by Django 5.2.3 on 2025-06-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_standard_name_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='standard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.standard'),
        ),
    ]
