# Generated by Django 5.2.3 on 2025-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_subject_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'standard')},
        ),
    ]
