# Generated by Django 5.2.3 on 2025-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('numerical', 'Numerical'), ('MCQ', 'Mutliple Choice Questions'), ('CBQ', 'Concept Based Questions'), ('CETLO', 'CETLO'), ('Learning Journey', 'Learning Journey'), ('ABL', 'ABL'), ('Translation', 'Translation')], max_length=255)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
    ]
