# Generated by Django 5.2.3 on 2025-06-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_questiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('theory', 'Theory'), ('numerical', 'Numerical'), ('MCQ', 'Mutliple Choice Questions'), ('CBQ', 'Concept Based Questions'), ('CET', 'Chapter End Test'), ('LO', 'Learning Outcome'), ('Learning Journey', 'Learning Journey'), ('ABL', 'Activity Based Learning.'), ('Translation', 'Translation')], max_length=255),
        ),
    ]
