# Generated by Django 5.2.3 on 2025-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_questiontype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomsLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.TextField(default='')),
            ],
            options={
                'db_table': 'blooms_level',
            },
        ),
    ]
