# Generated by Django 5.2.3 on 2025-07-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bloomslevel'),
        ('question', '0009_alter_questionanswer_difficulty_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionType',
            new_name='ServiceType',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='type',
            new_name='service_type',
        ),
        migrations.AlterModelTable(
            name='servicetype',
            table='service_types',
        ),
    ]
