# Generated by Django 5.2.3 on 2025-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_questiontype_servicetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='service_type',
            field=models.CharField(choices=[('objective 1 mark', 'Objective one mark'), ('subjective 1 mark', 'Subjective one mark'), ('subjective 2 mark', 'Subjective two mark'), ('subjective 4 mark', 'Subjective four mark'), ('case based', 'Case Based')], max_length=255),
        ),
    ]
