# Generated by Django 5.2.3 on 2025-09-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_type', models.CharField(default='custom', max_length=20)),
                ('activity_type', models.CharField(choices=[('classroom', 'Classroom'), ('meta_cognitive', 'Meta Cognitive')], max_length=50)),
                ('description', models.TextField(default='')),
                ('language', models.CharField(default='English', max_length=100)),
                ('activity_time_in_mins', models.IntegerField(default=15)),
                ('sub_subject_name', models.CharField(blank=True, max_length=50, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.board')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.chapter')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.standard')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.subject')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
