# Generated by Django 5.2.3 on 2025-09-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('utils', '0006_alter_chapter_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.classwisesubject'),
        ),
    ]
