# Generated by Django 5.2.3 on 2025-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='generation_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
