# Generated by Django 5.2.3 on 2025-09-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_generation_type'),
        ('utils', '0006_alter_chapter_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.servicetype'),
        ),
    ]
