# Generated by Django 5.2.3 on 2025-09-04 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompt', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradespecificprompt',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_specific_prompts', to='prompt.prompt'),
        ),
        migrations.AddField(
            model_name='promptdetail',
            name='base_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_detail_base_subject', to='utils.subject'),
        ),
        migrations.AddField(
            model_name='promptdetail',
            name='class_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_detail_class_end', to='utils.standard'),
        ),
        migrations.AddField(
            model_name='promptdetail',
            name='class_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_detail_class_start', to='utils.standard'),
        ),
        migrations.AddField(
            model_name='promptdetail',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt.prompt'),
        ),
        migrations.AddField(
            model_name='subjectspecificprompt',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_specific_prompts', to='prompt.prompt'),
        ),
        migrations.AddField(
            model_name='subjectspecificprompt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prompts', to='utils.subject'),
        ),
    ]
