# Generated by Django 5.2.3 on 2025-07-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_servicetype_service_type'),
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSpecificPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_specific_prompts', to='prompt.prompt')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_prompts', to='base.standard')),
            ],
            options={
                'db_table': 'grade_specifc_prompts',
            },
        ),
        migrations.CreateModel(
            name='SubjectSpecificPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_specific_prompts', to='prompt.prompt')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_prompts', to='base.subject')),
            ],
            options={
                'db_table': 'subject_specific_prompts',
            },
        ),
    ]
