# Generated by Django 5.2.3 on 2025-09-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_initial'),
        ('utils', '0002_chapter_board_alter_servicetype_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='service_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utils.servicetype'),
        ),
    ]
