# Generated by Django 5.2.3 on 2025-07-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_llmmodel'),
        ('prompt', '0002_gradespecificprompt_subjectspecificprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.llmmodel'),
        ),
    ]
