# Generated by Django 5.2.3 on 2025-09-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_alter_prompt_service_type'),
        ('utils', '0002_chapter_board_alter_servicetype_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptdetail',
            name='base_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_detail_base_subject', to='utils.subject'),
        ),
    ]
