# Generated by Django 5.2.3 on 2025-09-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0004_alter_promptdetail_base_subject'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promptdetail',
            table='prompt_details',
        ),
    ]
