# Generated by Django 5.2.3 on 2025-09-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_regeneration_attempt_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='regeneration_attempts',
        ),
    ]
