# Generated by Django 5.2.3 on 2025-09-04 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='')),
                ('language', models.CharField(default='English', max_length=100)),
                ('number_of_lo', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('generation_type', models.CharField(default='custom', max_length=20)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.board')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.chapter')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.standard')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.subject')),
            ],
            options={
                'db_table': 'learning_objectives',
            },
        ),
    ]
