# Generated by Django 5.2.3 on 2025-07-04 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_rename_questiontype_servicetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='')),
                ('language', models.CharField(default='English', max_length=100)),
                ('number_of_lo', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.board')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.chapter')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.standard')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
            ],
            options={
                'db_table': 'learning_objectives',
            },
        ),
    ]
