# Generated by Django 5.2.3 on 2025-07-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_objective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='generation_type',
            field=models.CharField(default='custom', max_length=20),
        ),
    ]
