# Generated by Django 5.2.3 on 2025-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_objective', '0002_learningobjective_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='generation_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
